---
vagrant_local:
  vm:
    name: oxideshop
    hostname: oxideshop.local
    aliases:
      - www.oxideshop.local
    app_shared_folder:
      source: oxideshop
      target: /var/www/oxideshop
server:
  packages:
    - git
landing:
  install: false
apache:
  docroot: "{{ eshop_path.source }}"
  servername: "{{ vagrant_local.vm.hostname }}"
mysql:
  root_password: oxid
  database: oxid
  user: oxid
  password: oxid
  grants: "`oxid%`.*:ALL"
php:
  version: 7.1
  zendguard:
    install: false
  packages:
    - bcmath
    - cli
    - curl
    - gd
    - intl
    - ldap
    - mbstring
    - mysql
    - soap
    - sqlite3
    - xml
    - zip
  composer:
    prestissimo:
      install: true
mailhog:
  install: true
adminer:
  install: true
adminer_editor:
  install: true
eshop_path:
  root: "{{ vagrant_local.vm.app_shared_folder.target }}"
  source: "{{ vagrant_local.vm.app_shared_folder.target }}/source"

